# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))

# scripts that run after cloning repository
install:
  - cinst atom
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm install"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm test --path %LOCALAPPDATA%/atom/bin/atom.cmd"

# to disable automatic tests
test: off

# to disable deployment
deploy: off
